import type { MediaSource } from "./types";

export const DEFAULT_KEYWORDS = [
  "半导体",
  "机器人",
  "人工智能",
  "中国宏观经济",
  "与中国有关的地缘新闻"
];

export const MEDIA_SOURCES: MediaSource[] = [
  { category: "官媒", name: "人民网经济·科技", url: "http://finance.people.com.cn/" },
  { category: "官媒", name: "新华网经济", url: "https://www.news.cn/fortune/index.htm" },
  { category: "官媒", name: "新华网科技", url: "https://www.news.cn/tech/" },
  { category: "官媒", name: "经济参考报", url: "https://www.jjckb.cn/" },
  { category: "官媒", name: "环球网", url: "https://www.huanqiu.com/" },
  { category: "官媒", name: "新华网时政联播", url: "https://www.news.cn/politics/szlb/index.html" },
  { category: "官媒", name: "中新网财经滚动", url: "https://www.chinanews.com.cn/cj/gd.shtml" },
  { category: "官媒", name: "中国经济网滚动消息", url: "http://www.ce.cn/2021sy/gd/index_1.shtml" },
  { category: "半导体产业门户", name: "全球半导体观察", url: "https://www.dramx.com/News/" },
  { category: "半导体产业门户", name: "半导体产业网", url: "https://www.casmita.com/news/" },
  { category: "半导体产业门户", name: "半导体新闻", url: "https://www.seminews.com.cn/news/" },
  { category: "半导体产业门户", name: "半导体行业观察", url: "https://www.163.com/dy/media/T1483516375236.html" },
  { category: "半导体产业门户", name: "半导体日报", url: "https://mp.weixin.qq.com/s/FQtw8XeUm1aHO8QgSnkVSQ" },
  { category: "半导体产业门户", name: "大半导体产业网", url: "https://www.semi.org.cn/site/semi/" },
  { category: "机器人产业门户", name: "机器人日报", url: "https://robot-daily.com/" },
  { category: "科技产业门户", name: "IT之家", url: "https://next.ithome.com/ai" },
  { category: "科技产业门户", name: "AIbase日报", url: "https://news.aibase.com/zh/daily" },
  { category: "科技产业门户", name: "全球科技地图", url: "http://www.globaltechmap.com/" },
  { category: "科技产业门户", name: "企业新闻周刊", url: "https://www.eweek.com/" },
  { category: "外媒", name: "联合早报中国板块", url: "https://www.zaobao.com.sg/news/china" },
  { category: "外媒", name: "路透社中国板块", url: "https://www.reuters.com/world/china/" },
  { category: "外媒", name: "南华早报中国板块", url: "https://www.scmp.com/news/china?module=oneline_menu_section_int&pgtype=homepage" },
  { category: "外媒", name: "彭博社政治板", url: "https://www.bloomberg.com/politics" },
  { category: "外媒", name: "商业时报", url: "https://www.businesstimes.com.sg/global?ref=logo" },
  { category: "宏观经济", name: "IMF", url: "https://www.imf.org/en/countries/chn" },
  { category: "宏观经济", name: "世界银行", url: "https://www.worldbank.org/ext/en/country/china" },
  { category: "宏观经济", name: "亚洲开发银行", url: "https://www.adb.org/news/adb-forecasts-resilient-gdp-growth-prc-2026-pick-inflation" },
  { category: "宏观经济", name: "高盛", url: "https://www.goldmansachs.com/insights" },
  { category: "宏观经济", name: "摩根士丹利", url: "https://www.morganstanley.com/insights/topics/market-trends" },
  { category: "宏观经济", name: "JP摩根周报", url: "https://am.jpmorgan.com/hk/en/asset-management/per/insights/market-insights/market-updates/weekly-market-recap/" },
  { category: "宏观经济", name: "瑞银", url: "https://www.ubs.com/global/en/investment-bank/insights-and-data/latest-insights.html" },
  { category: "宏观经济", name: "荣鼎", url: "https://rhg.com/china/" },
  { category: "宏观经济", name: "墨卡托", url: "https://merics.org/en/analysis" },
  { category: "宏观经济", name: "彼得森国际经济研究所", url: "https://www.piie.com/research/china" },
  { category: "宏观经济", name: "CSIS", url: "https://www.csis.org/programs/chinese-business-and-economics" },
  { category: "宏观经济", name: "布鲁金斯学会", url: "https://www.brookings.edu/regions/asia-the-pacific/china/" },
  { category: "宏观经济", name: "CFR", url: "https://www.cfr.org/regions/china" },
  { category: "宏观经济", name: "兰德", url: "https://www.rand.org/topics/china.html" },
  { category: "宏观经济", name: "ECFR", url: "https://ecfr.eu/asia/" },
  { category: "宏观经济", name: "查塔姆研究所", url: "https://www.chathamhouse.org/regions/asia-pacific/china" },
  { category: "宏观经济", name: "中国美国商会", url: "https://www.amchamchina.org/publications/" },
  { category: "宏观经济", name: "中国欧盟商会", url: "https://www.europeanchamber.com.cn/en/european-chamber-publications" }
];
